language: node_js

node_js:
  - 8
  - 10

services:
  - postgresql

script:
  - npm run build
  - test -z "$(git diff --raw)" # Check if `npm run build` created untracked changes (usually dist/*.d.ts)
  - npm test
  - npm run test:e2e
